### ISSUE TITLE
toggleFold() method doesn't exist 

### ISSUE THREAD

**Issue by svraluca** [faob-dev/folding_cell#11]
Hey , I get this error when I wrote the code , any idea how I can resolve it?
![Screenshot 2021-01-31 at 12 38 27](https://user-images.githubusercontent.com/61661732/106381187-e59f3980-636b-11eb-875c-3a6a4fb8c527.png)

**Comment by faob-dev** [comment]
Hi i cloned fresh project i am not getting any errors did you run pub get command? maybe closing and reopening project can fix this issue.

![image](https://user-images.githubusercontent.com/36742885/106872082-c0f0ec00-66f4-11eb-8d9d-abdc8089e3bc.png)

**Comment by faob-dev** [comment]
I am closing this issue feel free to reopen if you still have this issue
