### ISSUE TITLE
Not Working with ListView

### ISSUE THREAD

**Issue by mfabank** [faob-dev/folding_cell#13]
First, Thank you this package. It's a most beatiful for UI. But i have a question, i can't use this package with ListView class. Cards not opening. If i use key, showing me alert ("Multiple widgets used the same GlobalKey."). Please help me :)

**Comment by faob-dev** [comment]
Hi in example package there are 3 examples, one is listview demo and other is column demo can you check it. If you are still getting error please post code here i will fix it

**Comment by mfabank** [comment]
It' working. Thank you for your answers and package. :)

**Comment by faob-dev** [comment]
great i am closing this issue
