### ISSUE TITLE
[Question] Is it possible to use single inner widget?

### ISSUE THREAD

**Issue by rostopira** [faob-dev/folding_cell#4]
I have video-preview (e.g. closed cell) and I want to show play it when unfolded
Is it possible?

**Comment by faob-dev** [comment]
Hi do you want to play video when cell completely unfolded?

**Comment by faob-dev** [comment]
@rostopira `onOpen` and `onClose` added to package plus now you can programmatically open and close cell please check out example project.
I am planning to rewrite package and will consider inside single  widget.
Thanks

**Comment by rostopira** [comment]
I'm still not sure it's possible
`Transfrom` can't be applied to half of the widget, AFAIK

**Comment by faob-dev** [comment]
I have done it here 
https://twitter.com/faaoob/status/1073177025207255041

**Comment by faob-dev** [comment]
I am closing this issue `onOpen` and `onClose` added on your request and will consider inside single widget in next release

**Comment by faob-dev** [comment]
Added `SimpleFoldingCell.create()` to pass `frontWidget` and `innerWidget`
