### ISSUE TITLE
Card unfold state is not kept in a ListView

### ISSUE THREAD

**Issue by livotov** [faob-dev/folding_cell#7]
In a ListView, if I'll unfold one item and then scroll far down and then back - item state is lost and the card becomes folded again. Is there any way to fix this?

Otherwise - great plugin!

**Comment by faob-dev** [comment]
yes  Listview only creates objects that are visible and destroys all others you have to store cell `bool` state in your model object and there is `unfoldCell` property you can set that to your model property

**Comment by faob-dev** [comment]
I can create demo for you if you want?

**Comment by livotov** [comment]
Thanks, got it. No demo needed .
